version: "3.9"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./:/app

  vllm:
    build:
      context: ./vllm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ./vllm:/opt/app
    command: tail -f /dev/null
    stdin_open: true
    tty: true
